export const WALLET_CONNECT_REQUEST = "WALLET_CONNECT_REQUEST";
export const WALLET_CONNECT_SUCCESS = "WALLET_CONNECT_SUCCESS";
export const WALLET_CONNECT_ERROR = "WALLET_CONNECT_ERROR";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PARENT_CATEGORIES = "FETCH_PARENT_CATEGORIES";
export const FETCH_ITEMS = "FETCH_ITEMS";